#! /usr/bin/env ruby
#
class Lexer
  def initialize(f)
    @srcf = f
    @line = ""
  end

  def lex()
    if /\A\s+/ =~ @line
      @line = $'
    end

    while @line.empty? do
      @line = @srcf.gets
      if @line == nil
        return :eof
      end
      if /\A\s+/ =~ @line
        @line = $'
      end
    end


    case @line
    when /\Aint/
      yield $&
      token = :int
    when /\Astring/
      yield $&
      token = :string
    when /\A\d+/
      yield $&
      token = :num
    when /\A=/
      yield $&
      token = :eq
    when /\A\+/
      yield $&
      token = :plus
    when /\A\*/
      yield $&
      token = :mult
    when /\A\(/
      yield $&
      token = :lpar
    when /\A\)/
      yield $&
      token = :rpar
    when /\A\{/
      yield $&
      token = :lbrace
    when /\A\}/
      yield $&
      token = :rbrace
    when /\A[a-zA-Z]\w*/
      yield $&
      token = :id
    when /\A"\w*"/
      yield $&
      token = :lstring
    when /\A\;/
      yield $&
      token = :semi
    when /\A\S/
      #ignore
      token = :other
    end
    @line = $'
    return token
  end
end


